[package]
name = "embed-db"
version = "0.1.0"
edition = "2024"

[features]
default = [] # no_std by default
std = []     # Opt-in to std library and std-based storage

# default-features = false - we're saying: 
# Example:
# âŒ Don't enable thiserror's default features (which includes std)
# âœ… Only use the base no_std version
[dependencies]
thiserror = { version = "2.0.17", default-features = false }
bincode = { version = "2.0.1", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = { version = "1.0.145", default-features = false, features = [
    "alloc",
] }
serde = { version = "1.0.228", default-features = false, optional = false, features = [
    "derive",
] }

heapless = { version = "0.9.2", features = ["serde"] }
embedded-alloc = "0.6.0"
serde-json-core = "0.6.0"
uuid = { version = "1.18.1", features = ["v4"] }


[dev-dependencies]
criterion = { version = "0.5", default-features = false }

[[bench]]
name = "data_structures"
harness = false
required-features = ["std"]
