[package]
name = "embed-db"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
bincode = "2.0.1"
heapless = "0.9.2"
serde_json = "1.0.145"
criterion = "0.5"

[[bench]]
name = "data_structures"
harness = false